# Generated by Django 6.0.1 on 2026-04-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('packet_length', models.IntegerField()),
                ('packet_type', models.CharField(max_length=50)),
                ('traffic_type', models.CharField(max_length=50)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('attack_type', models.CharField(blank=True, max_length=100)),
                ('severity_level', models.CharField(blank=True, max_length=20)),
                ('user_information', models.CharField(blank=True, max_length=200)),
                ('network_segment', models.CharField(blank=True, max_length=50)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='threat_detection.networklog')),
            ],
        ),
    ]
