# Generated by Django 5.2.13 on 2026-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection', '0002_loginauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='log_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='networklog',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
